version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ColabManager'
      - 'POSTGRES_PASSWORD=senha1234'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - ./DBInit.sql:/docker-entrypoint-initdb.d/DBInit.sql
